In [1]:
import numpy as np

In [2]:
list_ = ['1','2','3','4','5']

In [3]:
array_list = np.array(object = list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [5]:
array_list.dtype

dtype('<U1')

The major difference between the list and the array is that , the list can contains the element of different data types while the array contain the element of same data types.

we cannot print the dtype for list as this functionality is not available

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [26]:
array_list.dtype

dtype('int32')

Q3. Considering the following changes in the variable, array_list:

In [10]:
array_list = np.array(object = list_, dtype = int)

In [11]:
array_list

array([1, 2, 3, 4, 5])

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [12]:
array_list.dtype

dtype('int32')

In [ ]:
# now the dtype for the array_list is int

In [14]:
num_list = [[1,2,3],[4,5,6]]

In [15]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [16]:
num_array = np.array(object = num_list)

In [17]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [19]:
num_array.shape

(2, 3)

In [20]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [21]:
num_arr = np.zeros((3,3))

In [22]:
num_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [24]:
identity_matrix = np.eye(5)

In [25]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])